#ifndef AXIS_PULSE_MOTOR_PARAMS_H
#define AXIS_PULSE_MOTOR_PARAMS_H

// X axis (Kinetix 5100 pulse-train input)
#define AXIS_X_ENCODER_PPR 10000
#define AXIS_X_MAX_PULSE_FREQ_HZ 200000
#define AXIS_X_GEAR_NUMERATOR 1.0f
#define AXIS_X_GEAR_DENOMINATOR 1.0f
#define AXIS_X_MOTOR_REDUCER_RATIO 1.0f
#define AXIS_X_INVERT_DIR 1
#define AXIS_X_INVERT_OUTPUT_LOGIC 1
#define AXIS_X_LEDC_RESOLUTION_BITS 2
#define AXIS_X_HOMING_SPEED_PPS 6000
#define AXIS_X_LIMIT_DEBOUNCE_CYCLES 10
#define AXIS_X_LIMIT_SAMPLE_INTERVAL_MS 3

// Y axis (Kinetix 5100 pulse-train input)
#define AXIS_Y_ENCODER_PPR 10000
#define AXIS_Y_MAX_PULSE_FREQ_HZ 200000
#define AXIS_Y_GEAR_NUMERATOR 1.0f
#define AXIS_Y_GEAR_DENOMINATOR 1.0f
#define AXIS_Y_MOTOR_REDUCER_RATIO 1.0f
#define AXIS_Y_INVERT_DIR 0
#define AXIS_Y_INVERT_OUTPUT_LOGIC 1
#define AXIS_Y_LEDC_RESOLUTION_BITS 2
#define AXIS_Y_HOMING_SPEED_PPS 6000
#define AXIS_Y_LIMIT_DEBOUNCE_CYCLES 10
#define AXIS_Y_LIMIT_SAMPLE_INTERVAL_MS 3

// Theta axis (custom pulse-train driver for SCHUNK ERD 04-40-D-H-N rotary)
#define AXIS_THETA_ENCODER_PPR 36000
#define AXIS_THETA_MAX_PULSE_FREQ_HZ 400000
#define AXIS_THETA_GEAR_NUMERATOR 1.0f
#define AXIS_THETA_GEAR_DENOMINATOR 1.0f
#define AXIS_THETA_MOTOR_REDUCER_RATIO 1.0f
#define AXIS_THETA_INVERT_DIR 0
#define AXIS_THETA_INVERT_OUTPUT_LOGIC 1
#define AXIS_THETA_LEDC_RESOLUTION_BITS 2

#endif  // AXIS_PULSE_MOTOR_PARAMS_H
