#!/usr/bin/env python3
"""Convert PDFs under driver_datasheets_and_calculations/ to markdown."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import pymupdf4llm

REPO_ROOT = Path(__file__).resolve().parents[1]
PDF_ROOT = REPO_ROOT / "driver_datasheets_and_calculations"
OUTPUT_ROOT = PDF_ROOT / "pdf_markdown"


def pdf_output_path(pdf_path: Path) -> Path:
    rel = pdf_path.relative_to(PDF_ROOT)
    return OUTPUT_ROOT / rel.with_suffix(".md")


def discover_pdfs(root: Path) -> list[Path]:
    skip_parts = {"pdf_markdown"}
    pdfs: list[Path] = []
    for path in sorted(root.rglob("*.pdf")):
        if skip_parts.intersection(path.relative_to(root).parts):
            continue
        pdfs.append(path)
    return pdfs


def convert_pdf(pdf_path: Path, *, force: bool = False) -> Path:
    out_path = pdf_output_path(pdf_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    if out_path.exists() and not force:
        print(f"skip  {pdf_path.name} (already converted)", flush=True)
        return out_path

    print(f"convert {pdf_path.relative_to(PDF_ROOT)}", flush=True)
    markdown = pymupdf4llm.to_markdown(str(pdf_path))

    header = (
        f"<!--\n"
        f"  Auto-generated from: {pdf_path.relative_to(REPO_ROOT).as_posix()}\n"
        f"  Generated by: tools/convert_pdfs_to_markdown.py\n"
        f"  Generated at: {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}\n"
        f"-->\n\n"
    )
    out_path.write_text(header + markdown, encoding="utf-8")
    print(f"  -> {out_path.relative_to(REPO_ROOT)} ({len(markdown):,} chars)", flush=True)
    return out_path


def write_index(pdfs: list[Path]) -> None:
    lines = [
        "# PDF markdown conversions",
        "",
        "Markdown extractions of PDFs in the parent folder. Regenerate with:",
        "",
        "```bash",
        "py tools/convert_pdfs_to_markdown.py",
        "```",
        "",
        "| Source PDF | Markdown |",
        "|------------|----------|",
    ]
    for pdf in pdfs:
        rel_pdf = pdf.relative_to(PDF_ROOT).as_posix()
        rel_md = pdf_output_path(pdf).relative_to(OUTPUT_ROOT).as_posix()
        lines.append(f"| `{rel_pdf}` | [{Path(rel_md).name}]({rel_md}) |")

    (OUTPUT_ROOT / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Reconvert even when the markdown file already exists.",
    )
    parser.add_argument(
        "pdfs",
        nargs="*",
        help="Optional PDF filenames or paths to convert (default: all under driver_datasheets_and_calculations).",
    )
    args = parser.parse_args(argv)

    if args.pdfs:
        pdfs: list[Path] = []
        for item in args.pdfs:
            path = Path(item)
            if not path.is_absolute():
                candidate = PDF_ROOT / path
                if candidate.exists():
                    path = candidate
                elif (REPO_ROOT / path).exists():
                    path = REPO_ROOT / path
            if not path.exists():
                print(f"error: not found: {item}", file=sys.stderr)
                return 1
            pdfs.append(path)
    else:
        pdfs = discover_pdfs(PDF_ROOT)

    if not pdfs:
        print("No PDFs found.", file=sys.stderr)
        return 1

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    for pdf in pdfs:
        convert_pdf(pdf, force=args.force)

    write_index(pdfs)
    print(f"\nDone. {len(pdfs)} file(s) -> {OUTPUT_ROOT.relative_to(REPO_ROOT)}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
